### ISSUE TITLE
mac iterm2下字体颜色显示异常

### ISSUE THREAD

**Issue by yeyuqiu** [SukkaW/nali-cli#5]
终端: iterm2 + oh-my-zsh，配色方案为solarized

![image](https://user-images.githubusercontent.com/10056735/85974584-709c0800-ba08-11ea-825e-3da874d73dd8.png)

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/85981838-6e8d7580-ba17-11ea-8360-bb9cfecfde1c.png)

Same on iTerm2.

It is the problem of your theme, not Nali CLI.
